ARG USER=vscode
ARG UID=1000
ARG GID=${UID}
ARG OCAMLVER=5.2.1

FROM debian:bookworm

ARG USER
ARG UID
ARG GID
ARG OCAMLVER

# Get additional tools/packages, e.g., for vscode
RUN apt-get update && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends \
    ca-certificates \
    curl \
    xz-utils \
    git \
    gnupg \
    locales \
    less \
    ssh \
    sudo \
    python3 python3-pip python3-venv python3-dev python3-matplotlib python3-jupyterlab-server \
    jupyter-notebook jupyter-core jupyter-client python3-ipykernel \
    sagemath sagemath-jupyter \
    libppl-dev pkg-config \
    build-essential autoconf automake cmake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
    libclang-dev llvm-dev \
    gawk build-essential bison flex texinfo gperf libtool patchutils bc \
    zlib1g-dev libexpat-dev \
    gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf \
    qemu-system-arm binutils-arm-none-eabi gcc-arm-none-eabi \
    libnewlib-arm-none-eabi libnewlib-dev \
    libstdc++-arm-none-eabi-dev libstdc++-arm-none-eabi-newlib \
    libusb-1.0-0-dev usbutils \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Create user
RUN groupadd -g ${GID} ${USER} && \
    useradd -u ${UID} -g ${GID} -G sudo -m ${USER} -s /bin/bash

# Configure sudo and Nix
RUN sed -i 's/%sudo.*ALL/%sudo   ALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

# Configure en_US.UTF-8 locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

USER ${USER}
ENV USER=${USER}

WORKDIR /workspace
CMD [ "bash" ]
